<?php

class FontsCustomFields {
	
	public function __construct() {
		self::setup_option_page();
		self::register_fields();
	}

	public static function setup_option_page() {
		if( function_exists('acf_add_options_page') ) {
			acf_add_options_sub_page(array(
        'page_title'  => 'Typography Settings',
        'menu_title'  => 'Typography',
        'parent_slug' => 'theme-general-settings',
      ));
    }
	}

	public static function register_fields() {
		if( function_exists('register_field_group') ):
			register_field_group(array (
          'key' => 'group_5419e3faf1616',
          'title' => 'Typography - Embed Code',
          'fields' => array (
            array (
              'key' => 'field_5419e99e1d489',
              'label' => 'Embed Code',
              'name' => 'fru_embed_code',
              'prefix' => '',
              'type' => 'textarea',
              'instructions' => 'Paste the embed code here if you are using external resources. This will be added into the <b>head</b> tag. <br>Quick links: <a href="https://typekit.com/fonts" target="_blank">Typekit</a>, <a href="http://www.typography.com/" target="_blank">Typography.com</a>, <a href="https://www.google.com/fonts" target="_blank">Google Web Fonts</a>',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'maxlength' => '',
              'rows' => 4,
              'new_lines' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
          ),
          'location' => array (
            array (
              array (
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'acf-options-typography',
              ),
            ),
          ),
          'menu_order' => 0,
          'position' => 'normal',
          'style' => 'default',
          'label_placement' => 'top',
          'instruction_placement' => 'label',
          'hide_on_screen' => '',
        ));

        register_field_group(array (
          'key' => 'group_5419eccd2892e',
          'title' => 'Typography - Font Family',
          'fields' => array (
            array (
              'key' => 'field_541afb9f700b0',
              'label' => 'Font Family',
              'name' => 'fru_font_family',
              'prefix' => '',
              'type' => 'flexible_content',
              'instructions' => 'Font family name may change depending on your font resources.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'button_label' => 'Add Font Family Styling',
              'min' => '',
              'max' => '',
              'layouts' => array (
                array (
                  'key' => '541afba414e26',
                  'name' => 'fru_body',
                  'label' => 'Body Text',
                  'display' => 'table',
                  'sub_fields' => array (
                    array (
                      'key' => 'field_541afbce700b1',
                      'label' => 'Body Font Family Name',
                      'name' => 'fru_body_font_family_name',
                      'prefix' => '',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 30,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                      'readonly' => 0,
                      'disabled' => 0,
                    ),
                    array (
                      'key' => 'field_541afc07700b2',
                      'label' => 'Body Font Family Fallback',
                      'name' => 'fru_body_font_fallback',
                      'prefix' => '',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 20,
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array (
                        'sans-serif' => 'sans-serif',
                        'serif' => 'serif',
                        'mono' => 'mono',
                      ),
                      'default_value' => array (
                        'serif' => 'serif',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'ajax' => 0,
                      'placeholder' => '',
                      'disabled' => 0,
                      'readonly' => 0,
                    ),
                    array (
                      'key' => 'field_541afc38700b3',
                      'label' => 'Body Font Size',
                      'name' => 'fru_body_font_size',
                      'prefix' => '',
                      'type' => 'number',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 10,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                      'readonly' => 0,
                      'disabled' => 0,
                    ),
                    array (
                      'key' => 'field_541afc73700b4',
                      'label' => 'Body Font Color',
                      'name' => 'fru_body_font_color',
                      'prefix' => '',
                      'type' => 'color_picker',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 40,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                    ),
                  ),
                  'min' => '',
                  'max' => 1,
                ),
                array (
                  'key' => '541b1d4bb9111',
                  'name' => 'fru_primary_menu_font',
                  'label' => 'Primary Menu',
                  'display' => 'table',
                  'sub_fields' => array (
                    array (
                      'key' => 'field_541b1d4bb9112',
                      'label' => 'Menu Font Family Name',
                      'name' => 'fru_primary_menu_font_family_name',
                      'prefix' => '',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 30,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                      'readonly' => 0,
                      'disabled' => 0,
                    ),
                    array (
                      'key' => 'field_541b1d4bb9113',
                      'label' => 'Menu Font Family Fallback',
                      'name' => 'fru_primary_menu_font_fallback',
                      'prefix' => '',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 20,
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array (
                        'sans-serif' => 'sans-serif',
                        'serif' => 'serif',
                        'mono' => 'mono',
                      ),
                      'default_value' => array (
                        'serif' => 'serif',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'ajax' => 0,
                      'placeholder' => '',
                      'disabled' => 0,
                      'readonly' => 0,
                    ),
                    array (
                      'key' => 'field_541b1d4bb9114',
                      'label' => 'Menu Font Size',
                      'name' => 'fru_primary_menu_font_size',
                      'prefix' => '',
                      'type' => 'number',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 10,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                      'readonly' => 0,
                      'disabled' => 0,
                    ),
                    array (
                      'key' => 'field_541b1d4bb9115',
                      'label' => 'Menu Font Color',
                      'name' => 'fru_primary_menu_font_color',
                      'prefix' => '',
                      'type' => 'color_picker',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 40,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                    ),
                  ),
                  'min' => '',
                  'max' => 1,
                ),
                array (
                  'key' => '541b18bb6bc89',
                  'name' => 'fru_heading_1',
                  'label' => 'Heading 1',
                  'display' => 'table',
                  'sub_fields' => array (
                    array (
                      'key' => 'field_541b18bb6bc8a',
                      'label' => 'H1 Font Family Name',
                      'name' => 'fru_h1_font_family_name',
                      'prefix' => '',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 30,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                      'readonly' => 0,
                      'disabled' => 0,
                    ),
                    array (
                      'key' => 'field_541b18bb6bc8b',
                      'label' => 'H1 Font Family Fallback',
                      'name' => 'fru_h1_font_fallback',
                      'prefix' => '',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 20,
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array (
                        'sans-serif' => 'sans-serif',
                        'serif' => 'serif',
                        'mono' => 'mono',
                      ),
                      'default_value' => array (
                        'serif' => 'serif',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'ajax' => 0,
                      'placeholder' => '',
                      'disabled' => 0,
                      'readonly' => 0,
                    ),
                    array (
                      'key' => 'field_541b18bb6bc8c',
                      'label' => 'H1 Font Size',
                      'name' => 'fru_h1_font_size',
                      'prefix' => '',
                      'type' => 'number',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 10,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                      'readonly' => 0,
                      'disabled' => 0,
                    ),
                    array (
                      'key' => 'field_541b18bb6bc8d',
                      'label' => 'H1 Font Color',
                      'name' => 'fru_h1_font_color',
                      'prefix' => '',
                      'type' => 'color_picker',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 40,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                    ),
                  ),
                  'min' => '',
                  'max' => 1,
                ),
                array (
                  'key' => '541afcebe92f4',
                  'name' => 'fru_heading_2',
                  'label' => 'Heading 2',
                  'display' => 'table',
                  'sub_fields' => array (
                    array (
                      'key' => 'field_541afcebe92f5',
                      'label' => 'H2 Font Family Name',
                      'name' => 'fru_h2_font_family_name',
                      'prefix' => '',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 30,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                      'readonly' => 0,
                      'disabled' => 0,
                    ),
                    array (
                      'key' => 'field_541afcebe92f6',
                      'label' => 'H2 Font Family Fallback',
                      'name' => 'fru_h2_font_fallback',
                      'prefix' => '',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 20,
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array (
                        'sans-serif' => 'sans-serif',
                        'serif' => 'serif',
                        'mono' => 'mono',
                      ),
                      'default_value' => array (
                        'serif' => 'serif',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'ajax' => 0,
                      'placeholder' => '',
                      'disabled' => 0,
                      'readonly' => 0,
                    ),
                    array (
                      'key' => 'field_541afcebe92f7',
                      'label' => 'H2 Font Size',
                      'name' => 'fru_h2_font_size',
                      'prefix' => '',
                      'type' => 'number',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 10,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                      'readonly' => 0,
                      'disabled' => 0,
                    ),
                    array (
                      'key' => 'field_541afcebe92f8',
                      'label' => 'H2 Font Color',
                      'name' => 'fru_h2_font_color',
                      'prefix' => '',
                      'type' => 'color_picker',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 40,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '#000000',
                    ),
                  ),
                  'min' => '',
                  'max' => 1,
                ),
                array (
                  'key' => '541b1412abc72',
                  'name' => 'fru_heading_3',
                  'label' => 'Heading 3',
                  'display' => 'table',
                  'sub_fields' => array (
                    array (
                      'key' => 'field_541b1412abc73',
                      'label' => 'H3 Font Family Name',
                      'name' => 'fru_h3_font_family_name',
                      'prefix' => '',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 30,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                      'readonly' => 0,
                      'disabled' => 0,
                    ),
                    array (
                      'key' => 'field_541b1412abc74',
                      'label' => 'H3 Font Family Fallback',
                      'name' => 'fru_h3_font_fallback',
                      'prefix' => '',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 20,
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array (
                        'sans-serif' => 'sans-serif',
                        'serif' => 'serif',
                        'mono' => 'mono',
                      ),
                      'default_value' => array (
                        'serif' => 'serif',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'ajax' => 0,
                      'placeholder' => '',
                      'disabled' => 0,
                      'readonly' => 0,
                    ),
                    array (
                      'key' => 'field_541b1412abc75',
                      'label' => 'H3 Font Size',
                      'name' => 'fru_h3_font_size',
                      'prefix' => '',
                      'type' => 'number',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 10,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                      'readonly' => 0,
                      'disabled' => 0,
                    ),
                    array (
                      'key' => 'field_541b1412abc76',
                      'label' => 'H3 Font Color',
                      'name' => 'fru_h3_font_color',
                      'prefix' => '',
                      'type' => 'color_picker',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 40,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '#000000',
                    ),
                  ),
                  'min' => '',
                  'max' => 1,
                ),
                array (
                  'key' => '541b1443abc77',
                  'name' => 'fru_heading_4',
                  'label' => 'Heading 4',
                  'display' => 'table',
                  'sub_fields' => array (
                    array (
                      'key' => 'field_541b1443abc78',
                      'label' => 'H4 Font Family Name',
                      'name' => 'fru_h4_font_family_name',
                      'prefix' => '',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 30,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                      'readonly' => 0,
                      'disabled' => 0,
                    ),
                    array (
                      'key' => 'field_541b1443abc79',
                      'label' => 'H4 Font Family Fallback',
                      'name' => 'fru_h4_font_fallback',
                      'prefix' => '',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 20,
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array (
                        'sans-serif' => 'sans-serif',
                        'serif' => 'serif',
                        'mono' => 'mono',
                      ),
                      'default_value' => array (
                        'serif' => 'serif',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'ajax' => 0,
                      'placeholder' => '',
                      'disabled' => 0,
                      'readonly' => 0,
                    ),
                    array (
                      'key' => 'field_541b1443abc7a',
                      'label' => 'H4 Font Size',
                      'name' => 'fru_h4_font_size',
                      'prefix' => '',
                      'type' => 'number',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 10,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                      'readonly' => 0,
                      'disabled' => 0,
                    ),
                    array (
                      'key' => 'field_541b1443abc7b',
                      'label' => 'H4 Font Color',
                      'name' => 'fru_h4_font_color',
                      'prefix' => '',
                      'type' => 'color_picker',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 40,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '#000000',
                    ),
                  ),
                  'min' => '',
                  'max' => 1,
                ),
                array (
                  'key' => '541b1460abc7c',
                  'name' => 'fru_heading_5',
                  'label' => 'Heading 5',
                  'display' => 'table',
                  'sub_fields' => array (
                    array (
                      'key' => 'field_541b1460abc7d',
                      'label' => 'H5 Font Family Name',
                      'name' => 'fru_h5_font_family_name',
                      'prefix' => '',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 30,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                      'readonly' => 0,
                      'disabled' => 0,
                    ),
                    array (
                      'key' => 'field_541b1460abc7e',
                      'label' => 'H5 Font Family Fallback',
                      'name' => 'fru_h5_font_fallback',
                      'prefix' => '',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 20,
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array (
                        'sans-serif' => 'sans-serif',
                        'serif' => 'serif',
                        'mono' => 'mono',
                      ),
                      'default_value' => array (
                        'serif' => 'serif',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'ajax' => 0,
                      'placeholder' => '',
                      'disabled' => 0,
                      'readonly' => 0,
                    ),
                    array (
                      'key' => 'field_541b1460abc7f',
                      'label' => 'H5 Font Size',
                      'name' => 'fru_h5_font_size',
                      'prefix' => '',
                      'type' => 'number',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 10,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                      'readonly' => 0,
                      'disabled' => 0,
                    ),
                    array (
                      'key' => 'field_541b1460abc80',
                      'label' => 'H5 Font Color',
                      'name' => 'fru_h5_font_color',
                      'prefix' => '',
                      'type' => 'color_picker',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 40,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '#000000',
                    ),
                  ),
                  'min' => '',
                  'max' => 1,
                ),
                array (
                  'key' => '541b147babc81',
                  'name' => 'fru_heading_6',
                  'label' => 'Heading 6',
                  'display' => 'table',
                  'sub_fields' => array (
                    array (
                      'key' => 'field_541b147babc82',
                      'label' => 'H6 Font Family Name',
                      'name' => 'fru_h6_font_family_name',
                      'prefix' => '',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 30,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                      'readonly' => 0,
                      'disabled' => 0,
                    ),
                    array (
                      'key' => 'field_541b147babc83',
                      'label' => 'H6 Font Family Fallback',
                      'name' => 'fru_h6_font_fallback',
                      'prefix' => '',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 20,
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array (
                        'sans-serif' => 'sans-serif',
                        'serif' => 'serif',
                        'mono' => 'mono',
                      ),
                      'default_value' => array (
                        'serif' => 'serif',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'ajax' => 0,
                      'placeholder' => '',
                      'disabled' => 0,
                      'readonly' => 0,
                    ),
                    array (
                      'key' => 'field_541b147babc84',
                      'label' => 'H6 Font Size',
                      'name' => 'fru_h6_font_size',
                      'prefix' => '',
                      'type' => 'number',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 10,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'min' => '',
                      'max' => '',
                      'step' => '',
                      'readonly' => 0,
                      'disabled' => 0,
                    ),
                    array (
                      'key' => 'field_541b147babc85',
                      'label' => 'H6 Font Color',
                      'name' => 'fru_h6_font_color',
                      'prefix' => '',
                      'type' => 'color_picker',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => 40,
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '#000000',
                    ),
                  ),
                  'min' => '',
                  'max' => 1,
                ),
              ),
            ),
          ),
          'location' => array (
            array (
              array (
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'acf-options-typography',
              ),
            ),
          ),
          'menu_order' => 2,
          'position' => 'normal',
          'style' => 'seamless',
          'label_placement' => 'top',
          'instruction_placement' => 'label',
          'hide_on_screen' => '',
        ));
		endif;
	}

}

new FontsCustomFields;